package kr.hhplus.be.server.unit.domain.payment.model;

import kr.hhplus.be.server.payment.domain.model.Payment;
import kr.hhplus.be.server.payment.domain.model.PaymentMethod;
import kr.hhplus.be.server.payment.domain.model.PaymentStatus;
import kr.hhplus.be.server.reservation.domain.model.Reservation;
import kr.hhplus.be.server.unit.BaseUnitTest;
import kr.hhplus.be.server.unit.fixture.PaymentFixture;
import kr.hhplus.be.server.unit.fixture.ReservationFixture;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Clock;
import java.time.ZoneId;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

public class PaymentTest extends BaseUnitTest {
    @Test
    @DisplayName("createPending creates a pending payment")
    void createPending_shouldCreatePendingPayment() {
        Reservation reservation = ReservationFixture.reservation(fixedUUID());
        int amount = 40000;

        Payment payment = Payment.createPending(reservation, amount, PaymentMethod.CARD);

        // The id is generated by JPA when the entity is persisted.
        assertNull(payment.getId());
        assertEquals(reservation, payment.getReservation());
        assertEquals(amount, payment.getAmount());
        assertEquals(PaymentMethod.CARD, payment.getMethod());
        assertEquals(PaymentStatus.PENDING, payment.getStatus());
        assertNull(payment.getPaidAt());
        assertFalse(payment.isDeleted());
        assertNull(payment.getCreatedAt());
        assertNull(payment.getUpdatedAt());
    }

    @Test
    @DisplayName("createPaid creates a paid payment")
    void createPaid_shouldCreatePaidPayment() {
        Reservation reservation = ReservationFixture.reservation(fixedUUID());
        int amount = 40000;

        ZoneId zone = ZoneId.systemDefault();
        Clock clock = Clock.fixed(fixedNow().atZone(zone).toInstant(), zone);

        Payment payment = Payment.createPaid(reservation, amount, PaymentMethod.CARD, clock);

        assertNull(payment.getId());
        assertEquals(reservation, payment.getReservation());
        assertEquals(amount, payment.getAmount());
        assertEquals(PaymentMethod.CARD, payment.getMethod());
        assertEquals(PaymentStatus.PAID, payment.getStatus());
        assertEquals(fixedNow(), payment.getPaidAt());
        assertFalse(payment.isDeleted());
        assertNull(payment.getCreatedAt());
        assertNull(payment.getUpdatedAt());
    }

    @Test
    @DisplayName("paid payment keeps payment details")
    void paidPayment_shouldKeepDetails() {
        Reservation reservation = ReservationFixture.reservation(fixedUUID());

        Payment payment = PaymentFixture.paid(fixedUUID(), reservation, 55000, PaymentMethod.CARD, fixedNow());

        assertEquals(fixedUUID(), payment.getId());
        assertEquals(reservation, payment.getReservation());
        assertEquals(55000, payment.getAmount());
        assertEquals(PaymentMethod.CARD, payment.getMethod());
        assertEquals(PaymentStatus.PAID, payment.getStatus());
        assertNotNull(payment.getPaidAt());
        assertFalse(payment.isDeleted());
        assertNull(payment.getCreatedAt());
        assertNull(payment.getUpdatedAt());
    }

    @Test
    @DisplayName("hasSameRequest compares amount and method")
    void hasSameRequest_shouldCompareAmountAndMethod() {
        Payment payment = PaymentFixture.request(55000, PaymentMethod.CARD);

        assertEquals(true, payment.hasSameRequest(55000, PaymentMethod.CARD));
        assertEquals(false, payment.hasSameRequest(55001, PaymentMethod.CARD));
        assertEquals(false, payment.hasSameRequest(55000, PaymentMethod.CASH));
    }
}
